Make PHP 8.3 default version
ramsalt/drupal-scaffold pull request #30
Opened 2023-11-24 08:06 UTC by jfauske

2024-05-29 15:51 UTC, szeidler requested changes

2024-05-29 15:51 UTC, szeidler commented on assets/renovate.json
>    "force": {
@jfauske Should we get rid off the deprecated `force` constraint and solve it from composer-side for new projects?

2024-06-01 13:54 UTC, jfauske commented on assets/renovate.json
>    "force": {
Yes! Removed in a31cde28ad8711cb51446ae7395a67fe155667e7

2024-06-03 17:21 UTC, szeidler approved these changes

2024-06-04 12:59 UTC, merged